FROM node:22-alpine AS base
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM base AS dev
WORKDIR /app
COPY . .
EXPOSE 5173
CMD ["pnpm", "dev:web"]

FROM base AS build
WORKDIR /app
ARG VITE_SOCKET_URL=https://car-socket.infiniter.tech
ENV VITE_SOCKET_URL=${VITE_SOCKET_URL}
COPY . .
RUN pnpm build:web

FROM nginx:1.29-alpine AS production
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
