services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: production
    environment:
      PORT: 3001
      ALLOWED_ORIGIN: https://car.infiniter.tech,https://www.car.infiniter.tech
    ports:
      - "13331:3001"
